openapi: 3.0.0
info:
  title: Location API
  version: 1.0.0
  contact:
    name: User Management API Support
tags:
  - name: Location
    description: Operations related to User object.

paths:
  /locations/me:
    put:
      tags:
        - Location
      operationId: updateLocation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLocation'
        required: true
      responses:
        200:
          description: Location updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserLocation"

components:
  schemas:
    UserLocation:
      type: object
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double

