openapi: 3.0.3

info:
  title: Microservice Template API
  version: 1.4.0

paths:
  /v1/accounts:
    post:
      tags:
        - accounts
      operationId: createAccount
      parameters:
        - name: requestId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccount'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountId'
    get:
      tags:
        - accounts
      operationId: getAccounts
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
  /v1/accounts/{accountId}:
    get:
      tags:
        - accounts
      operationId: getAccount
      parameters:
        - name: accountId
          in: path
          description: Account identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Not found

components:
  schemas:
    CreateAccount:
      type: object
      properties:
        number:
          type: string
          description: 'Account number'
        customerId:
          type: string
          description: 'Customer identifier'
      required:
        - number
        - customerId
    AccountId:
      type: object
      properties:
        id:
          type: string
          description: 'Account identifier'
    Account:
      type: object
      properties:
        id:
          type: string
          description: 'Account identifier'
        number:
          type: string
          description: 'Account number'
        customerId:
          type: string
          description: 'Customer identifier'
        customerName:
          type: string
          description: 'Customer name'
        version:
          type: integer
          description: 'Account version'
