openapi: 3.0.0
info:
  title: Dinter User Profile Management API
  version: 1.0.0
  contact:
    name: User Profile Management API Support
tags:
  - name: UserProfile
    description: Operations related to UserProfile object.
servers:
  - url: http://{camHost}/v1
    variables:
      camHost:
        default: localhost
        description: Service host for exposing the service to internal services.

paths:
  /profiles:
    get:
      summary: GET v1/users/profile
      operationId: getUsersProfiles
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        200:
          description: Users found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfile'
        400:
          description: 'Users profile not found'
          content:
            application/json:
              schema:
                $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'
    post:
        summary: POST v1/users/profile
        operationId: createUserProfile
        requestBody:
            content:
              application/json:
                  schema:
                    $ref: '#/components/schemas/UserProfile'
            required: true
        responses:
            201:
              description: User profile creat ed
              content:
                  application/json:
                    schema:
                        $ref: '#/components/schemas/UserProfile'
            400:
              description: 'User profile not found'
              content:
                  application/json:
                    schema:
                      $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'
    put:
      summary: PUT v1/users/profile
      operationId: updateUserProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
        required: true
      responses:
        200:
          description: User profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        400:
          description: 'User profile not found'
          content:
            application/json:
              schema:
                $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'
  /profiles/{userId}:
    get:
        summary: GET v1/users/profile/{userId}
        operationId: getUserProfile
        parameters:
            - name: userId
              in: path
              description: Profile id to get user profile
              required: true
              schema:
                  type: string
        responses:
            200:
              description: User profile found
              content:
                  application/json:
                    schema:
                        $ref: '#/components/schemas/UserProfile'
            400:
              description: 'User profile not found'
              content:
                  application/json:
                    schema:
                        $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'

  /profiles/preferences:
    post:
        summary: POST v1/users/preferences
        operationId: createUserPreference
        requestBody:
            content:
              application/json:
                  schema:
                    $ref: '#/components/schemas/UserPreference'
            required: true
        responses:
            201:
              description: User preferences created
              content:
                  application/json:
                    schema:
                        $ref: '#/components/schemas/UserPreference'
            400:
              description: 'User preferences not found'
              content:
                  application/json:
                    schema:
                        $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'
    put:
      summary: PUT v1/users/preferences
      operationId: updateUserPreferences
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPreference'
        required: true
      responses:
        200:
          description: User preferences updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPreference'
        400:
          description: 'User bad request'
          content:
            application/json:
              schema:
                $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'
  /profiles/preferences/{userId}:
    get:
      summary: GET v1/users/preferences
      operationId: getUsersPreference
      parameters:
        - name: userId
          in: path
          description: User preference id to get user preference
          required: true
          schema:
            type: string
      responses:
        200:
          description: Users preferences found
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/UserPreference'
        400:
          description: 'Users preferences not found'
          content:
            application/json:
              schema:
                $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'


components:
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        userPreference:
          $ref: '#/components/schemas/UserPreference'
        avatarImageUrl:
          type: string
        displayName:
          type: string
          maxLength: 255
        birthDate:
          type: string
          format: date-time
        gender:
          type: boolean
        education:
          type: string
          maxLength: 255
        jobTitle:
          type: string
          maxLength: 255
        companyName:
          type: string
          maxLength: 255
        about:
          type: string
          maxLength: 1024
      required:
        - userId
        - avatarImageUrl
        - displayName
        - birthDate
        - gender
        
    UserPreference:
        type: object
        properties:
          id:
            type: string
          userId:
            type: string
          gender:
            type: boolean
          distance:
            type: integer
          ageFrom:
            type: integer
            minimum:  18
            maximum: 100
          ageTo:
            type: integer
          createdDate:
            type: string
            format: date-time
          updatedDate:
            type: string
            format: date-time
        required:
          - id
          - userId
          - gender
          - distance
          - ageFrom
          - ageFrom



