openapi: 3.0.0
info:
  title: Dinter User Energy API
  version: 0.0.1
  contact:
    name: User Energy API Support
tags:
  - name: Energy
    description: Operations related to user energy.
servers:
  - url: http://{camHost}/v1
    variables:
      camHost:
        default: localhost
        description: Service host for exposing the service to internal services.

paths:
  /energy/{userId}:
    get:
      summary: GET v1/energy/{userId}
      operationId: getUserEnergy
      parameters:
        - name: userId
          in: path
          description: User id to get user energy
          required: true
          schema:
              type: string
      responses:
        200:
          description: User energy found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEnergy'
        400:
          description: 'User energy not found'
          content:
            application/json:
              schema:
                $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'
    put:
      summary: PUT v1/energy/{userId}
      operationId: updateUserEnergy
      parameters:
        - name: userId
          in: path
          description: User id to increase user energy
          required: true
          schema:
              type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserEnergy'
        required: true
      responses:
        200:
          description: User energy increased
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEnergy'
        400:
          description: 'Invalid payload data'
          content:
            application/json:
              schema:
                $ref: '../../common/error.yaml#/components/schemas/ErrorResponse'

components:
  schemas:
    UserEnergy:
        type: object
        properties:
          userId:
            type: string
          amount:
            type: number
          timestamp:
            type: string
            format: date-time
        required:
            - userId
            - amount
            - timestamp
    UpdateUserEnergy:
      type: object
      properties:
        userId:
          type: string
        amount:
          type: number
        changeType:
          $ref: '#/components/schemas/ChangeType'
        timestamp:
          type: string
          format: date-time
      required:
        - userId
        - energyType
        - amount
        - requestType
        - timestamp
    ChangeType:
      description: To determine whether this is auto increment energy or purchased energy
      type: string
      default: UNKNOWN
      enum:
        - AUTO
        - MATCHING
        - PURCHASED
        - ADS
        - UNKNOWN
